version: '3'

services: 
  property:
    build:
        context: ./property_service
        dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    restart: always
    stdin_open: true
    tty: true
    networks: 
      - overlay
    ports:
      - "8888:8888"
    volumes:
      - "./property_service:/home/app/property/src/"
  
  user:
    build:
      context: ./user_service
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    restart: always
    stdin_open: true
    tty: true
    networks: 
      - overlay
    ports:
      - "8081:8081"
    volumes:
      - "./user_service:/home/app/user/src"

      
volumes: 
  db-config:
  db-data:

networks: 
    overlay: