version: '3'

services: 
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_DATABASE: "property"
      MYSQL_ROOT_PASSWORD: password
    #command: --init-file /home/init.sql
    #command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
      - ./dumps:/docker-entrypoint-initdb.d
      #- ./property.sql:/home/property.sql
      #- ./property.sql:/home/init.sql
    networks: 
      - overlay

  property:
    build:
        context: ./property_service
        dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    restart: always
    stdin_open: true
    tty: true
    networks: 
      - overlay
    ports:
      - "8888:8888"
    volumes:
      - "./property_service:/home/app/property/src/"
  
  user:
    build:
      context: ./user_service
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    restart: always
    depends_on:
        - mysqldb
    stdin_open: true
    tty: true
    networks: 
      - overlay
    ports:
      - "8081:8081"
    volumes:
      - "./user_service:/home/app/user/src"

      
volumes: 
  db-config:
  db-data:

networks: 
    overlay: