apiVersion: eksctl.io/v1
kind: ClusterConfig
metadata:
  name: property
  region: ap-south-1

vpc:
  id: vpc-09ca7ed83f2d27f0d
  cidr: "192.168.0.0/16"
  subnets:
    public:
      ap-south-1a:
        id: subnet-0e162b486ac2074a8
      ap-south-1b:
        id: subnet-0adf1b391979a16b0
    private:
      ap-south-1a:
        id: subnet-0d8348f80a2eac5ac
      ap-south-1b:
        id: subnet-04b9900b6708b835c

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.micro
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.micro
    desiredCapacity: 1
    privateNetworking: true